language: node_js
node_js:
  - "stable"

branches:
  only:
    - dep-inclusions   # ✅ your active branch for this lab

cache:
  directories:
    - node_modules

install:
  - npm install --legacy-peer-deps
  - npm install -g yarn

script:
  # - yarn lint   # (keep commented for now)
  - yarn build
  - mv build/index.html build/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: dep-inclusions   # ✅ must match the branch you’re working in
